export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const ADD_SHOPPING_LIST = 'ADD_SHOPPING_LIST';
export const FETCH_SHOPPING_LIST = 'FETCH_SHOPPING_LIST';
export const COMPLETE_SHOPPING_ITEM = 'COMPLETE_SHOPPING_ITEM';
export const DELETE_SHOPPING_ITEM = 'DELETE_SHOPPING_ITEM';